"""Provider-neutral, bounded Search Fabric contracts."""

from .contracts import (
    MAX_QUERY_BYTES,
    MAX_SEARCH_BACKENDS,
    MAX_SEARCH_EVIDENCE,
    MAX_SEARCH_JSON_BYTES,
    SearchCorroborationState,
    SearchEngineErrorV1,
    SearchEvidenceV1,
    SearchFabricContractError,
    SearchFabricJsonCodec,
    SearchFetchState,
    SearchFreshnessState,
    SearchIntent,
    SearchResultV1,
    SearchSourceClass,
    SearchVendorFeeClass,
    query_digest,
)
from .gateway import (
    LoopbackAddress,
    LoopbackSearchFabricGateway,
    LoopbackSearchPostRequest,
    LoopbackSearchPostResponse,
    LoopbackSearchPostTransport,
    SearchFabricGatewayError,
)
from .receipts import SearchGatewayOutcome, SearchReceiptV1, opaque_search_request_id
from .composition import (
    AiohttpLoopbackSearchHealthProbe,
    LocalSearchFabricRuntime,
    SearchCompositionError,
    build_local_search_fabric_runtime,
)
from .orchestrator import (
    SearchAuthorizationError,
    SearchOrchestrator,
    SearchOrchestratorOutcome,
    SearchOrchestratorPolicy,
    SearchVerificationState,
    build_search_synthesis_prompt,
    classify_search_intent,
    search_synthesis_evidence,
    search_source_display_title,
    search_query_is_high_stakes,
    search_verification_notice,
)

__all__ = [
    "MAX_QUERY_BYTES",
    "MAX_SEARCH_BACKENDS",
    "MAX_SEARCH_EVIDENCE",
    "MAX_SEARCH_JSON_BYTES",
    "LoopbackAddress",
    "LoopbackSearchFabricGateway",
    "LoopbackSearchPostRequest",
    "LoopbackSearchPostResponse",
    "LoopbackSearchPostTransport",
    "AiohttpLoopbackSearchHealthProbe",
    "LocalSearchFabricRuntime",
    "SearchAuthorizationError",
    "SearchCompositionError",
    "SearchEngineErrorV1",
    "SearchCorroborationState",
    "SearchEvidenceV1",
    "SearchFabricContractError",
    "SearchFabricGatewayError",
    "SearchFabricJsonCodec",
    "SearchFetchState",
    "SearchFreshnessState",
    "SearchGatewayOutcome",
    "SearchIntent",
    "SearchOrchestrator",
    "SearchOrchestratorOutcome",
    "SearchOrchestratorPolicy",
    "SearchReceiptV1",
    "SearchResultV1",
    "SearchSourceClass",
    "SearchVendorFeeClass",
    "SearchVerificationState",
    "build_search_synthesis_prompt",
    "build_local_search_fabric_runtime",
    "classify_search_intent",
    "query_digest",
    "opaque_search_request_id",
    "search_synthesis_evidence",
    "search_source_display_title",
    "search_query_is_high_stakes",
    "search_verification_notice",
]
