from __future__ import annotations


VOICEVOX_SPEAKER_ID = 3
VOICEVOX_ALLOWED_SPEAKER_IDS = frozenset({VOICEVOX_SPEAKER_ID})
MIN_VOICEVOX_WAV_BYTES = 48_044


__all__ = [
    "MIN_VOICEVOX_WAV_BYTES",
    "VOICEVOX_ALLOWED_SPEAKER_IDS",
    "VOICEVOX_SPEAKER_ID",
]
