"""監査可能な静的runtime manifest fragments。"""

from .admin_ui import CAPABILITIES as ADMIN_UI_CAPABILITIES
from .ai_memory import CAPABILITIES as AI_MEMORY_CAPABILITIES
from .browser_rendering import CAPABILITIES as BROWSER_RENDERING_CAPABILITIES
from .community import CAPABILITIES as COMMUNITY_CAPABILITIES
from .capability_forge import CAPABILITIES as CAPABILITY_FORGE_CAPABILITIES
from .discovery import CAPABILITIES as DISCOVERY_CAPABILITIES
from .earthquake import CAPABILITIES as EARTHQUAKE_CAPABILITIES
from .image_editing import CAPABILITIES as IMAGE_EDITING_CAPABILITIES
from .jp_information import CAPABILITIES as JP_INFORMATION_CAPABILITIES
from .image_generation import CAPABILITIES as IMAGE_GENERATION_CAPABILITIES
from .moderation_server import CAPABILITIES as MODERATION_SERVER_CAPABILITIES
from .modules import MODULES as RUNTIME_MODULES
from .music_audio import CAPABILITIES as MUSIC_AUDIO_CAPABILITIES
from .media_pipeline import CAPABILITIES as MEDIA_PIPELINE_CAPABILITIES
from .media_inspection import CAPABILITIES as MEDIA_INSPECTION_CAPABILITIES
from .music_generation import CAPABILITIES as MUSIC_GENERATION_CAPABILITIES
from .nasa_apod import CAPABILITIES as NASA_APOD_CAPABILITIES
from .site_publish import CAPABILITIES as SITE_PUBLISH_CAPABILITIES
from .speech_synthesis import CAPABILITIES as SPEECH_SYNTHESIS_CAPABILITIES
from .speech_transcription import CAPABILITIES as SPEECH_TRANSCRIPTION_CAPABILITIES
from .system_ops import CAPABILITIES as SYSTEM_OPS_CAPABILITIES
from .types import RuntimeCapabilityDefinition, RuntimeModuleDefinition
from .utility import CAPABILITIES as UTILITY_CAPABILITIES
from .video_generation import CAPABILITIES as VIDEO_GENERATION_CAPABILITIES
from .web_search import CAPABILITIES as WEB_SEARCH_CAPABILITIES


CAPABILITY_FRAGMENTS: tuple[tuple[str, tuple[RuntimeCapabilityDefinition, ...]], ...] = (
    ("admin_ui", ADMIN_UI_CAPABILITIES),
    ("ai_memory", AI_MEMORY_CAPABILITIES),
    ("browser_rendering", BROWSER_RENDERING_CAPABILITIES),
    ("earthquake", EARTHQUAKE_CAPABILITIES),
    ("music_audio", MUSIC_AUDIO_CAPABILITIES),
    ("media_pipeline", MEDIA_PIPELINE_CAPABILITIES),
    ("media_inspection", MEDIA_INSPECTION_CAPABILITIES),
    ("site_publish", SITE_PUBLISH_CAPABILITIES),
    ("system_ops", SYSTEM_OPS_CAPABILITIES),
    ("community", COMMUNITY_CAPABILITIES),
    ("capability_forge", CAPABILITY_FORGE_CAPABILITIES),
    ("utility", UTILITY_CAPABILITIES),
    ("moderation_server", MODERATION_SERVER_CAPABILITIES),
    ("discovery", DISCOVERY_CAPABILITIES),
    ("jp_information", JP_INFORMATION_CAPABILITIES),
    ("nasa_apod", NASA_APOD_CAPABILITIES),
    ("image_editing", IMAGE_EDITING_CAPABILITIES),
    ("image_generation", IMAGE_GENERATION_CAPABILITIES),
    ("music_generation", MUSIC_GENERATION_CAPABILITIES),
    ("speech_synthesis", SPEECH_SYNTHESIS_CAPABILITIES),
    ("speech_transcription", SPEECH_TRANSCRIPTION_CAPABILITIES),
    ("video_generation", VIDEO_GENERATION_CAPABILITIES),
    ("web_search", WEB_SEARCH_CAPABILITIES),
)

RUNTIME_CAPABILITIES: tuple[RuntimeCapabilityDefinition, ...] = (
    *ADMIN_UI_CAPABILITIES,
    *AI_MEMORY_CAPABILITIES,
    *BROWSER_RENDERING_CAPABILITIES,
    *EARTHQUAKE_CAPABILITIES,
    *MUSIC_AUDIO_CAPABILITIES,
    *MEDIA_PIPELINE_CAPABILITIES,
    *MEDIA_INSPECTION_CAPABILITIES,
    *SITE_PUBLISH_CAPABILITIES,
    *SYSTEM_OPS_CAPABILITIES,
    *COMMUNITY_CAPABILITIES,
    *CAPABILITY_FORGE_CAPABILITIES,
    *UTILITY_CAPABILITIES,
    *MODERATION_SERVER_CAPABILITIES,
    *DISCOVERY_CAPABILITIES,
    *JP_INFORMATION_CAPABILITIES,
    *NASA_APOD_CAPABILITIES,
    *IMAGE_EDITING_CAPABILITIES,
    *IMAGE_GENERATION_CAPABILITIES,
    *MUSIC_GENERATION_CAPABILITIES,
    *SPEECH_SYNTHESIS_CAPABILITIES,
    *SPEECH_TRANSCRIPTION_CAPABILITIES,
    *VIDEO_GENERATION_CAPABILITIES,
    *WEB_SEARCH_CAPABILITIES,
)


__all__ = [
    "CAPABILITY_FRAGMENTS",
    "RUNTIME_CAPABILITIES",
    "RUNTIME_MODULES",
    "RuntimeCapabilityDefinition",
    "RuntimeModuleDefinition",
]
