from __future__ import annotations

from ..control_plane import RbacLevel, RiskLevel
from .types import RuntimeCapabilityDefinition, _cap


CAPABILITIES: tuple[RuntimeCapabilityDefinition, ...] = (
    # Moderation: high/destructiveはguild設定でも権限下限を緩和できない。
    _cap(
        "cap-run-mod-warn",
        "moderation.actions",
        "警告をcase ledgerへ記録",
        command="mod warn",
        level=RbacLevel.MODERATOR,
        risk=RiskLevel.HIGH,
    ),
    _cap(
        "cap-run-mod-warnings",
        "moderation.actions",
        "警告履歴を表示",
        command="mod warnings",
        level=RbacLevel.MODERATOR,
        risk=RiskLevel.MEDIUM,
    ),
    _cap(
        "cap-run-mod-timeout",
        "moderation.actions",
        "memberをtimeout",
        command="mod timeout",
        level=RbacLevel.GUILD_ADMIN,
        risk=RiskLevel.CRITICAL,
    ),
    _cap(
        "cap-run-mod-untimeout",
        "moderation.actions",
        "memberのtimeoutを解除",
        command="mod untimeout",
        level=RbacLevel.MODERATOR,
        risk=RiskLevel.HIGH,
    ),
    _cap(
        "cap-run-mod-kick",
        "moderation.actions",
        "memberをkick",
        command="mod kick",
        level=RbacLevel.GUILD_ADMIN,
        risk=RiskLevel.CRITICAL,
    ),
    _cap(
        "cap-run-mod-ban",
        "moderation.actions",
        "memberをban",
        command="mod ban",
        level=RbacLevel.GUILD_ADMIN,
        risk=RiskLevel.CRITICAL,
    ),
    _cap(
        "cap-run-mod-unban",
        "moderation.actions",
        "banを解除",
        command="mod unban",
        level=RbacLevel.GUILD_ADMIN,
        risk=RiskLevel.HIGH,
    ),
    _cap(
        "cap-run-mod-purge",
        "moderation.actions",
        "messageを確認付きで一括削除",
        command="mod purge",
        level=RbacLevel.GUILD_ADMIN,
        risk=RiskLevel.CRITICAL,
    ),
    _cap(
        "cap-run-mod-purge-user",
        "moderation.actions",
        "特定userのmessageを確認付きで削除",
        command="mod purge-user",
        level=RbacLevel.GUILD_ADMIN,
        risk=RiskLevel.CRITICAL,
    ),
    _cap(
        "cap-run-mod-purge-links",
        "moderation.actions",
        "URL投稿を確認付きで削除",
        command="mod purge-links",
        level=RbacLevel.GUILD_ADMIN,
        risk=RiskLevel.CRITICAL,
    ),
    _cap(
        "cap-run-mod-case",
        "moderation.actions",
        "moderation caseを表示",
        command="mod case",
        level=RbacLevel.MODERATOR,
        risk=RiskLevel.MEDIUM,
    ),
    # Server management and its event listeners.
    _cap(
        "cap-run-server-slowmode",
        "security.access-control",
        "channel slowmodeを設定",
        command="server slowmode",
        level=RbacLevel.GUILD_ADMIN,
        risk=RiskLevel.HIGH,
    ),
    _cap(
        "cap-run-server-lock",
        "security.access-control",
        "channelをlock",
        command="server lock",
        level=RbacLevel.GUILD_ADMIN,
        risk=RiskLevel.HIGH,
    ),
    _cap(
        "cap-run-server-unlock",
        "security.access-control",
        "channelをunlock",
        command="server unlock",
        level=RbacLevel.GUILD_ADMIN,
        risk=RiskLevel.HIGH,
    ),
    _cap(
        "cap-run-server-nick",
        "security.access-control",
        "member nicknameを変更",
        command="server nick",
        level=RbacLevel.MODERATOR,
        risk=RiskLevel.HIGH,
    ),
    _cap(
        "cap-run-server-role-add",
        "security.access-control",
        "memberへroleを追加",
        command="server role-add",
        level=RbacLevel.GUILD_ADMIN,
        risk=RiskLevel.CRITICAL,
    ),
    _cap(
        "cap-run-server-role-remove",
        "security.access-control",
        "memberからroleを削除",
        command="server role-remove",
        level=RbacLevel.GUILD_ADMIN,
        risk=RiskLevel.CRITICAL,
    ),
    _cap(
        "cap-run-server-announce",
        "security.access-control",
        "mentionを制限して告知",
        command="server announce",
        level=RbacLevel.GUILD_ADMIN,
        risk=RiskLevel.HIGH,
    ),
    _cap(
        "cap-run-server-welcome-set",
        "security.access-control",
        "welcome messageを設定",
        command="server welcome-set",
        level=RbacLevel.GUILD_ADMIN,
        risk=RiskLevel.HIGH,
    ),
    _cap(
        "cap-run-server-goodbye-set",
        "security.access-control",
        "goodbye messageを設定",
        command="server goodbye-set",
        level=RbacLevel.GUILD_ADMIN,
        risk=RiskLevel.HIGH,
    ),
    _cap(
        "cap-run-server-log-channel",
        "security.access-control",
        "server監査log channelを設定",
        command="server log-channel",
        level=RbacLevel.GUILD_ADMIN,
        risk=RiskLevel.HIGH,
    ),
    _cap(
        "cap-run-server-config-show",
        "security.access-control",
        "servertools設定を表示",
        command="server config-show",
        level=RbacLevel.GUILD_ADMIN,
        risk=RiskLevel.MEDIUM,
    ),
    _cap(
        "cap-run-server-member-join",
        "security.access-control",
        "member join時のwelcome通知",
        event="member_join",
        plugin="servertools",
        risk=RiskLevel.MEDIUM,
    ),
    _cap(
        "cap-run-server-member-remove",
        "security.access-control",
        "member remove時のgoodbye通知",
        event="member_remove",
        plugin="servertools",
        risk=RiskLevel.MEDIUM,
    ),
    _cap(
        "cap-run-server-message-delete",
        "security.access-control",
        "message削除を監査channelへ通知",
        event="message_delete",
        plugin="servertools",
        level=RbacLevel.GUILD_ADMIN,
        risk=RiskLevel.HIGH,
    ),
    _cap(
        "cap-run-server-message-edit",
        "security.access-control",
        "message編集を監査channelへ通知",
        event="message_edit",
        plugin="servertools",
        level=RbacLevel.GUILD_ADMIN,
        risk=RiskLevel.HIGH,
    ),
)
