from __future__ import annotations

from ..control_plane import RiskLevel
from .types import RuntimeCapabilityDefinition, _cap


CAPABILITIES: tuple[RuntimeCapabilityDefinition, ...] = (
    _cap(
        "cap-run-audio-ducking-core",
        "media.audio-core",
        "48kHz PCMで音楽とTTSを合成し、発話中だけ音楽を滑らかにducking",
        plugin="music",
        risk=RiskLevel.MEDIUM,
    ),
    _cap(
        "cap-run-music-status",
        "media.music",
        "音楽・TTS・ローカルlibraryの利用状態を表示",
        command="music status",
        plugin="music",
    ),
    _cap(
        "cap-run-music-join",
        "media.music",
        "利用者と同じVCへ音楽playerを接続",
        command="music join",
        plugin="music",
        risk=RiskLevel.MEDIUM,
        dependencies=("cap-run-audio-ducking-core",),
    ),
    _cap(
        "cap-run-music-leave",
        "media.music",
        "権限を持つ利用者が音楽sessionを終了してVCから退出",
        command="music leave",
        plugin="music",
        risk=RiskLevel.MEDIUM,
        dependencies=("cap-run-audio-ducking-core",),
    ),
    _cap(
        "cap-run-music-play",
        "media.music",
        "許可済みローカルlibraryから曲名でqueueへ追加・再生",
        command="music play",
        plugin="music",
        risk=RiskLevel.MEDIUM,
        dependencies=("cap-run-audio-ducking-core",),
    ),
    _cap(
        "cap-run-music-import",
        "media.music",
        "権利確認済みPCM WAV添付をcontent-addressed private libraryへ取り込む",
        command="music import",
        plugin="music",
        risk=RiskLevel.MEDIUM,
        dependencies=("cap-run-audio-ducking-core",),
    ),
    _cap(
        "cap-run-music-search",
        "media.music",
        "許可済みローカルlibraryを曲名で検索",
        command="music search",
        plugin="music",
        dependencies=("cap-run-audio-ducking-core",),
    ),
    _cap(
        "cap-run-music-now",
        "media.music",
        "現在の再生曲を表示",
        command="music now",
        plugin="music",
        dependencies=("cap-run-audio-ducking-core",),
    ),
    _cap(
        "cap-run-music-queue",
        "media.music",
        "現在曲と待機queueを表示",
        command="music queue",
        plugin="music",
        dependencies=("cap-run-audio-ducking-core",),
    ),
    _cap(
        "cap-run-music-pause",
        "media.music",
        "音楽busだけを一時停止しTTS busは継続",
        command="music pause",
        plugin="music",
        risk=RiskLevel.MEDIUM,
        dependencies=("cap-run-audio-ducking-core",),
    ),
    _cap(
        "cap-run-music-resume",
        "media.music",
        "一時停止中の音楽busを再開",
        command="music resume",
        plugin="music",
        risk=RiskLevel.MEDIUM,
        dependencies=("cap-run-audio-ducking-core",),
    ),
    _cap(
        "cap-run-music-skip",
        "media.music",
        "現在曲の依頼者または管理者が曲をskip",
        command="music skip",
        plugin="music",
        risk=RiskLevel.MEDIUM,
        dependencies=("cap-run-audio-ducking-core",),
    ),
    _cap(
        "cap-run-music-stop",
        "media.music",
        "音楽とqueueだけを停止しTTSは継続",
        command="music stop",
        plugin="music",
        risk=RiskLevel.MEDIUM,
        dependencies=("cap-run-audio-ducking-core",),
    ),
    _cap(
        "cap-run-music-radio",
        "media.music",
        "許可済みローカルlibraryから手動queue優先で1曲ずつ自動補充",
        command="music radio",
        plugin="music",
        risk=RiskLevel.MEDIUM,
        dependencies=("cap-run-audio-ducking-core",),
    ),
    _cap(
        "cap-run-music-seek",
        "media.music",
        "現在曲の依頼者または管理者がlocal音源の再生位置を変更",
        command="music seek",
        plugin="music",
        risk=RiskLevel.MEDIUM,
        dependencies=("cap-run-audio-ducking-core",),
    ),
    _cap(
        "cap-run-music-remove",
        "media.music",
        "本人のqueue曲または管理者が指定曲を削除",
        command="music remove",
        plugin="music",
        risk=RiskLevel.MEDIUM,
        dependencies=("cap-run-audio-ducking-core",),
    ),
    _cap(
        "cap-run-music-move",
        "media.music",
        "本人のqueue曲または管理者が待機queue内の位置を変更",
        command="music move",
        plugin="music",
        risk=RiskLevel.MEDIUM,
        dependencies=("cap-run-audio-ducking-core",),
    ),
    _cap(
        "cap-run-music-clear-mine",
        "media.music",
        "本人が依頼した待機queue曲だけを一括削除",
        command="music clear-mine",
        plugin="music",
        risk=RiskLevel.MEDIUM,
        dependencies=("cap-run-audio-ducking-core",),
    ),
    _cap(
        "cap-run-music-shuffle",
        "media.music",
        "現在曲の依頼者または管理者が待機queueをshuffle",
        command="music shuffle",
        plugin="music",
        risk=RiskLevel.MEDIUM,
        dependencies=("cap-run-audio-ducking-core",),
    ),
    _cap(
        "cap-run-music-loop",
        "media.music",
        "現在曲の依頼者または管理者がtrack・queue loopを設定",
        command="music loop",
        plugin="music",
        risk=RiskLevel.MEDIUM,
        dependencies=("cap-run-audio-ducking-core",),
    ),
    _cap(
        "cap-run-music-volume",
        "media.music",
        "現在曲の依頼者または管理者が音楽またはTTS bus音量を設定",
        command="music volume",
        plugin="music",
        risk=RiskLevel.MEDIUM,
        dependencies=("cap-run-audio-ducking-core",),
    ),
    _cap(
        "cap-run-music-speak",
        "media.music",
        "VOICEVOXをリアルタイム合成し音楽ducking付きでVCへ重畳",
        command="music speak",
        plugin="music",
        risk=RiskLevel.MEDIUM,
        dependencies=("cap-run-audio-ducking-core", "cap-can-0416"),
    ),
    RuntimeCapabilityDefinition(
        capability_id="cap-run-music-read-aloud-message",
        module_id="media.music",
        name="明示routeの短文をloopback VOICEVOXで合成し既存music sessionへducking付きで重畳",
        command_paths=(
            "music read-aloud enable",
            "music read-aloud disable",
            "music read-aloud focus-start",
            "music read-aloud focus-cancel",
            "music read-aloud list",
            "music read-aloud dictionary-set",
            "music read-aloud dictionary-delete",
            "music read-aloud exclude-add",
            "music read-aloud exclude-delete",
            "music read-aloud policy",
            "music read-aloud server-preset",
            "music read-aloud my-preset",
            "music read-aloud preset",
        ),
        event_names=("music_read_aloud_message",),
        plugin="music",
        risk=RiskLevel.MEDIUM,
        default_enabled=False,
        dependencies=("cap-run-audio-ducking-core", "cap-can-0416"),
    ),
    _cap(
        "cap-run-music-search-youtube",
        "media.music",
        "YouTube公式検索ページURLを生成（音声抽出・再配信なし）",
        command="music search-youtube",
        plugin="music",
    ),
    _cap(
        "cap-run-music-playlist-save",
        "media.music",
        "本人の現在曲とqueueを個人playlistへ保存",
        command="music playlist save",
        plugin="music",
        risk=RiskLevel.MEDIUM,
        dependencies=("cap-run-audio-ducking-core",),
    ),
    _cap(
        "cap-run-music-playlist-list",
        "media.music",
        "本人所有のplaylistだけを表示",
        command="music playlist list",
        plugin="music",
    ),
    _cap(
        "cap-run-music-playlist-load",
        "media.music",
        "本人のplaylistを許可済みlibraryで再解決してqueueへ追加",
        command="music playlist load",
        plugin="music",
        risk=RiskLevel.MEDIUM,
        dependencies=("cap-run-audio-ducking-core",),
    ),
    _cap(
        "cap-run-music-playlist-delete",
        "media.music",
        "本人所有のplaylistを削除",
        command="music playlist delete",
        plugin="music",
        risk=RiskLevel.MEDIUM,
    ),
)
