from __future__ import annotations

from ..control_plane import RbacLevel, RiskLevel
from .types import RuntimeCapabilityDefinition, _cap


CAPABILITIES: tuple[RuntimeCapabilityDefinition, ...] = (
    _cap(
        "cap-run-yonerai-status",
        "operations.observability",
        "YonerAI将来連携のread-only境界状態を表示",
        command="yonerai status",
        plugin="yonerai",
        level=RbacLevel.GUILD_ADMIN,
        risk=RiskLevel.MEDIUM,
    ),
    _cap(
        "cap-run-yonerai-health",
        "operations.observability",
        "許可済みYonerAI readiness contractだけを照会",
        command="yonerai health",
        plugin="yonerai",
        level=RbacLevel.GUILD_ADMIN,
        risk=RiskLevel.MEDIUM,
    ),
    _cap(
        "cap-run-verify-status",
        "security.access-control",
        "本人確認の安全設定とguild側状態を表示",
        command="verify status",
        plugin="identity",
    ),
    _cap(
        "cap-run-verify-start",
        "security.access-control",
        "本人専用の短時間ワンタイム認証URLを発行",
        command="verify start",
        plugin="identity",
        risk=RiskLevel.MEDIUM,
        default_enabled=False,
    ),
    _cap(
        "cap-run-verify-configure",
        "security.access-control",
        "安全なverified roleとguild側switchを設定",
        command="verify configure",
        plugin="identity",
        level=RbacLevel.GUILD_ADMIN,
        risk=RiskLevel.CRITICAL,
        default_enabled=False,
    ),
    _cap(
        "cap-run-jobs-status",
        "operations.execution",
        "durable job workerとqueue状態を表示",
        command="jobs status",
        plugin="jobs",
        level=RbacLevel.GUILD_ADMIN,
        risk=RiskLevel.MEDIUM,
    ),
    _cap(
        "cap-run-jobs-list",
        "operations.execution",
        "payloadを隠してdurable job一覧を表示",
        command="jobs list",
        plugin="jobs",
        level=RbacLevel.GUILD_ADMIN,
        risk=RiskLevel.MEDIUM,
    ),
    _cap(
        "cap-run-jobs-retry",
        "operations.execution",
        "terminal jobを監査付きで再queue",
        command="jobs retry",
        plugin="jobs",
        level=RbacLevel.GUILD_ADMIN,
        risk=RiskLevel.HIGH,
    ),
    _cap(
        "cap-run-jobs-cancel",
        "operations.execution",
        "未実行durable jobを監査付きでcancel",
        command="jobs cancel",
        plugin="jobs",
        level=RbacLevel.GUILD_ADMIN,
        risk=RiskLevel.HIGH,
    ),
    _cap(
        "cap-run-jobs-execute",
        "operations.execution",
        "allowlist済みexecutorだけをdurable workerで実行",
        event="worker.jobs-execute",
        plugin="jobs",
        level=RbacLevel.GUILD_ADMIN,
        risk=RiskLevel.HIGH,
    ),
    _cap(
        "cap-run-automod-status",
        "moderation.automod",
        "report-only AutoModの状態を表示",
        command="automod status",
        plugin="automod",
        level=RbacLevel.GUILD_ADMIN,
        risk=RiskLevel.MEDIUM,
    ),
    _cap(
        "cap-run-automod-channel",
        "moderation.automod",
        "AutoModのredacted report channelを設定",
        command="automod channel",
        plugin="automod",
        level=RbacLevel.GUILD_ADMIN,
        risk=RiskLevel.HIGH,
    ),
    _cap(
        "cap-run-automod-policy",
        "moderation.automod",
        "確認文字列付きでreport-only policyをON/OFF",
        command="automod policy",
        plugin="automod",
        level=RbacLevel.GUILD_ADMIN,
        risk=RiskLevel.HIGH,
    ),
    _cap(
        "cap-run-automod-message-create",
        "moderation.automod",
        "message createを本文非保存でreport-only検知",
        event="automod_message_create",
        plugin="automod",
        level=RbacLevel.GUILD_ADMIN,
        risk=RiskLevel.HIGH,
        default_enabled=False,
    ),
    _cap(
        "cap-run-automod-message-edit",
        "moderation.automod",
        "message editを本文非保存でreport-only再検査",
        event="automod_message_edit",
        plugin="automod",
        level=RbacLevel.GUILD_ADMIN,
        risk=RiskLevel.HIGH,
        default_enabled=False,
    ),
    _cap(
        "cap-run-schedule-uncertain",
        "operations.scheduling-notification",
        "重複防止で保留したreminder配信を表示",
        command="schedule uncertain",
        plugin="scheduling",
        level=RbacLevel.BOT_OWNER,
        risk=RiskLevel.HIGH,
        owner_only=True,
    ),
    _cap(
        "cap-run-schedule-resolve",
        "operations.scheduling-notification",
        "uncertain reminderを所有者が監査後に解決",
        command="schedule resolve",
        plugin="scheduling",
        level=RbacLevel.BOT_OWNER,
        risk=RiskLevel.CRITICAL,
        default_enabled=False,
        owner_only=True,
    ),
    _cap(
        "cap-run-minecraft-status",
        "gaming.minecraft",
        "設定済みMinecraft Java serverのstatusをread-onlyで取得",
        command="minecraft status",
        plugin="minecraft",
    ),
    _cap(
        "cap-run-system-audit",
        "operations.observability",
        "append-only監査logを表示",
        command="system audit",
        level=RbacLevel.GUILD_ADMIN,
        risk=RiskLevel.HIGH,
    ),
    _cap(
        "cap-run-system-overrides",
        "operations.observability",
        "guildのmodule/capability/RBAC overrideを表示",
        command="system overrides",
        level=RbacLevel.GUILD_ADMIN,
        risk=RiskLevel.HIGH,
    ),
    _cap(
        "cap-run-system-runtime",
        "operations.observability",
        "実tree/plugin/handler inventoryを表示",
        command="system runtime",
        level=RbacLevel.GUILD_ADMIN,
        risk=RiskLevel.HIGH,
    ),
    _cap(
        "cap-run-system-backup",
        "data.storage",
        "SQLite online backupとquick_checkを実行",
        command="system backup",
        level=RbacLevel.BOT_OWNER,
        risk=RiskLevel.CRITICAL,
        owner_only=True,
    ),
    # Self-evolution: status以外は設定・capability overrideの二重opt-in。
    _cap(
        "cap-run-evolution-status",
        "intelligence.ai-runtime",
        "自己進化review基盤の状態を表示",
        command="evolution status",
        level=RbacLevel.BOT_OWNER,
        owner_only=True,
    ),
    _cap(
        "cap-run-evolution-propose",
        "intelligence.ai-runtime",
        "Solで改善proposal artifactを作成",
        command="evolution propose",
        level=RbacLevel.BOT_OWNER,
        risk=RiskLevel.HIGH,
        default_enabled=False,
        owner_only=True,
    ),
    _cap(
        "cap-run-evolution-review",
        "intelligence.ai-runtime",
        "自己進化proposalのreviewを開始",
        command="evolution review",
        level=RbacLevel.BOT_OWNER,
        risk=RiskLevel.HIGH,
        default_enabled=False,
        owner_only=True,
    ),
    _cap(
        "cap-run-evolution-approve",
        "intelligence.ai-runtime",
        "自己進化proposalを承認済みにする",
        command="evolution approve",
        level=RbacLevel.BOT_OWNER,
        risk=RiskLevel.HIGH,
        default_enabled=False,
        owner_only=True,
    ),
    _cap(
        "cap-run-evolution-reject",
        "intelligence.ai-runtime",
        "自己進化proposalを却下",
        command="evolution reject",
        level=RbacLevel.BOT_OWNER,
        risk=RiskLevel.HIGH,
        default_enabled=False,
        owner_only=True,
    ),
    _cap(
        "cap-run-evolution-show",
        "intelligence.ai-runtime",
        "自己進化proposal artifactを検証して表示",
        command="evolution show",
        level=RbacLevel.BOT_OWNER,
        risk=RiskLevel.HIGH,
        default_enabled=False,
        owner_only=True,
    ),
)
