"""Typed broker boundary for managed sandbox capabilities."""

from .broker import CapabilityBroker, InMemoryCapabilityAuditSink
from .contract import (
    ApprovalClass,
    ArtifactDescriptor,
    ArtifactKind,
    AuditOutcome,
    AuditRecord,
    BackendCleanupReceipt,
    BackendExecution,
    BackendStatus,
    BrokerResult,
    CapabilityArtifact,
    CapabilityAuditError,
    CapabilityAuthorizationError,
    CapabilityBinding,
    CapabilityBrokerError,
    CapabilityBrokerStatus,
    CapabilityCleanupError,
    CapabilityContractError,
    CapabilityIdempotencyError,
    CapabilityKind,
    CapabilityRequest,
    CapabilityTimeoutError,
    CapabilityUnavailableError,
    CleanupReason,
    ExecutionReceipt,
    ExecutionStatus,
    MediaCapabilityInput,
    NetworkPolicy,
    PermissionClass,
    ResourceLimits,
)
from .discord_media import BrokeredDiscordMediaInspectionAdapter, SQLiteCapabilityAuditSink
from .hyperv_media import (
    HYPERV_MEDIA_BACKEND_ID,
    HYPERV_MEDIA_IDENTITY_DIGEST,
    HyperVMediaManagedBackend,
)


__all__ = [
    "ApprovalClass",
    "ArtifactDescriptor",
    "ArtifactKind",
    "AuditOutcome",
    "AuditRecord",
    "BackendCleanupReceipt",
    "BackendExecution",
    "BackendStatus",
    "BrokerResult",
    "BrokeredDiscordMediaInspectionAdapter",
    "CapabilityArtifact",
    "CapabilityAuditError",
    "CapabilityAuthorizationError",
    "CapabilityBinding",
    "CapabilityBroker",
    "CapabilityBrokerError",
    "CapabilityBrokerStatus",
    "CapabilityCleanupError",
    "CapabilityContractError",
    "CapabilityIdempotencyError",
    "CapabilityKind",
    "CapabilityRequest",
    "CapabilityTimeoutError",
    "CapabilityUnavailableError",
    "CleanupReason",
    "ExecutionReceipt",
    "ExecutionStatus",
    "HYPERV_MEDIA_BACKEND_ID",
    "HYPERV_MEDIA_IDENTITY_DIGEST",
    "HyperVMediaManagedBackend",
    "InMemoryCapabilityAuditSink",
    "MediaCapabilityInput",
    "NetworkPolicy",
    "PermissionClass",
    "ResourceLimits",
    "SQLiteCapabilityAuditSink",
]
