"""気象庁と内閣府の固定公式 endpoint を使う日本向け公開情報 module。"""

from __future__ import annotations

from typing import Any

from .adapter import (
    DEFAULT_CAPABILITY_IDS,
    HOLIDAY_NEXT_CAPABILITY_ID,
    HOLIDAY_YEAR_CAPABILITY_ID,
    WARNING_CAPABILITY_ID,
    WEATHER_CAPABILITY_ID,
    DiscordJpInformationAdapter,
    HolidayGroup,
    JpInformationAdapter,
    JpInformationCapabilityIds,
    escape_discord_text,
    render_holiday_year,
    render_next_holiday,
    render_warning,
    render_weather,
)
from .client import (
    AREA_URL,
    CAO_HOLIDAY_CSV_URL,
    DEFAULT_CONNECT_TIMEOUT_SECONDS,
    DEFAULT_TOTAL_TIMEOUT_SECONDS,
    FORECAST_URL_TEMPLATE,
    HOLIDAY_CSV_URL,
    JMA_AREA_URL,
    JMA_FORECAST_URL_TEMPLATE,
    JMA_WARNING_URL_TEMPLATE,
    MAX_HOLIDAY_RESPONSE_BYTES,
    MAX_JMA_RESPONSE_BYTES,
    WARNING_URL_TEMPLATE,
    CabinetOfficeHolidayClient,
    HolidayClient,
    JMAClient,
    JmaClient,
    decode_holiday_csv,
)
from .domain import (
    ForecastPeriod,
    Holiday,
    HolidayCalendar,
    HolidayYear,
    Region,
    RegionCatalog,
    WarningItem,
    WarningReport,
    WeatherForecast,
    normalize_region_query,
    parse_holiday_csv,
    parse_jma_datetime,
    parse_region_catalog,
    parse_warning_report,
    parse_weather_forecast,
)
from .errors import (
    CircuitOpenError,
    InvalidPayloadError,
    JpInformationError,
    ProviderBusyError,
    PublishedRangeError,
    RedirectRejectedError,
    ResponseTooLargeError,
    TransportError,
    UnknownRegionError,
)
from .plugin import InformationPlugin, JP_INFORMATION_PLUGIN_NAME, JpInformationPlugin
from .service import (
    HOLIDAY_CACHE_TTL_SECONDS,
    JMA_AREA_CACHE_TTL_SECONDS,
    JMA_FORECAST_CACHE_TTL_SECONDS,
    JMA_WARNING_CACHE_TTL_SECONDS,
    AsyncTTLCache,
    InformationService,
    JpInformationService,
    ProviderGuard,
    ProviderSnapshot,
)


def setup(manager: Any) -> None:
    register = getattr(manager, "register_plugin", None) or getattr(manager, "register", None)
    if register is None:
        raise TypeError("manager must provide register_plugin() or register()")
    register(JP_INFORMATION_PLUGIN_NAME, JpInformationPlugin)


__all__ = [
    "AREA_URL",
    "CAO_HOLIDAY_CSV_URL",
    "DEFAULT_CAPABILITY_IDS",
    "DEFAULT_CONNECT_TIMEOUT_SECONDS",
    "DEFAULT_TOTAL_TIMEOUT_SECONDS",
    "FORECAST_URL_TEMPLATE",
    "HOLIDAY_CACHE_TTL_SECONDS",
    "HOLIDAY_CSV_URL",
    "HOLIDAY_NEXT_CAPABILITY_ID",
    "HOLIDAY_YEAR_CAPABILITY_ID",
    "JP_INFORMATION_PLUGIN_NAME",
    "JMA_AREA_CACHE_TTL_SECONDS",
    "JMA_AREA_URL",
    "JMA_FORECAST_CACHE_TTL_SECONDS",
    "JMA_FORECAST_URL_TEMPLATE",
    "JMA_WARNING_CACHE_TTL_SECONDS",
    "JMA_WARNING_URL_TEMPLATE",
    "MAX_HOLIDAY_RESPONSE_BYTES",
    "MAX_JMA_RESPONSE_BYTES",
    "WARNING_CAPABILITY_ID",
    "WARNING_URL_TEMPLATE",
    "WEATHER_CAPABILITY_ID",
    "AsyncTTLCache",
    "CabinetOfficeHolidayClient",
    "CircuitOpenError",
    "DiscordJpInformationAdapter",
    "ForecastPeriod",
    "Holiday",
    "HolidayCalendar",
    "HolidayClient",
    "HolidayGroup",
    "HolidayYear",
    "InformationPlugin",
    "InformationService",
    "InvalidPayloadError",
    "JMAClient",
    "JmaClient",
    "JpInformationAdapter",
    "JpInformationCapabilityIds",
    "JpInformationError",
    "JpInformationPlugin",
    "JpInformationService",
    "ProviderBusyError",
    "ProviderGuard",
    "ProviderSnapshot",
    "PublishedRangeError",
    "RedirectRejectedError",
    "Region",
    "RegionCatalog",
    "ResponseTooLargeError",
    "TransportError",
    "UnknownRegionError",
    "WarningItem",
    "WarningReport",
    "WeatherForecast",
    "decode_holiday_csv",
    "escape_discord_text",
    "normalize_region_query",
    "parse_holiday_csv",
    "parse_jma_datetime",
    "parse_region_catalog",
    "parse_warning_report",
    "parse_weather_forecast",
    "render_holiday_year",
    "render_next_holiday",
    "render_warning",
    "render_weather",
    "setup",
]
